approve_by_comment: true
approve_regex: '^(Approved|:shipit:|:\+1:|LGTM)'
reject_regex: '^(Rejected|:-1:)'
reset_on_push: false
reviewers:
  members:
  - pastorsj
  - Prescientje
  name: pullapprove
  required: 1